truncate table public.rec_codigo;

insert into public.rec_codigo (id, descricao) values
('0013','Taxa Fiscalização CVM'),
('0019','Transferências Correntes dos Municípios'),
('0026','IRRF-Rendimentos do Trabalho de Qualquer Natureza, como os Provenientes de Pensão, Aposentadoria, Prêmios em Concursos e Comissões-Residentes no Exterior-Oper. Intra Orçament.'),
('0030','Alienação do Domínio Direto - SPU'),
('0039','IRRF-Remuneração Serviços Prestados por Pessoa Jurídica-Operações Intra Orçamentárias'),
('0041','Multa por Atraso na Entrega da Dirf Anual-Operações Intra Orçamentárias'),
('0046','Permissão de Uso - SPU'),
('0052','Regularização de depósitos extrajudiciais não tributários - Lei nº 12.099/2009'),
('0054','Multa por Atraso na Entrega da Dipj-Operações Intraorçamentárias'),
('0067','Produtos-Retenção em Pagamentos por Órgãos Públicos-Operações Intra Orçamentárias'),
('0069','Cessão de Uso - SPU'),
('0070','Transporte de Passageiros-Retenção em Pagamentos por Órgãos Públicos-Operações Intra Orçamentárias'),
('0075','Ressarcimento Casa da Moeda - Lei 11.488/2007'),
('0081','Indenização por Posse/Ocupação Ilícita - SPU'),
('0082','Financeiras-Retenção em Pagamentos por Órgãos Públicos-Operações Intra Orçamentárias'),
('0086','II - Imposto Importação - outros'),
('0094','II - Imposto Importação - Bagagem Acompanhada'),
('0095','Serviços-Retenção em Pagamentos por Órgãos Públicos-Operações Intra Orçamentárias'),
('0107','IE - Imposto Exportação - outros'),
('0110','Medicamentos Adquiridos do Distribuidor ou Varejista-Retido por Órgão Público-Operações Intra Orçamentárias'),
('0122','Transporte Internacional de Passageiros-Empresas Nacionais-Retido por Órgão Público-Operações Intra Orçamentárias'),
('0123','Bens e serviços adquiridos de sociedades cooperativas e associações profissionais ou assemelhadas - Retido por órgão público - Operações Intra-orçamentárias'),
('0135','Contribuição sobre Receita de Loteria de Prognóstico Específico'),
('0148','Cide - Combustíveis - Importação - Lançamento de Ofício'),
('0163','Receita dos Direitos Antidumping e dos Direitos Compensatórios - Depósito Judicial'),
('0174','Receita dos Direitos Antidumping e dos Direitos Compensatórios - Depósito Administrativo'),
('0176','R D Ativa - Parcelamento Timemania - Clubes de Futebol'),
('0190','IRPF - Carnê Leão'),
('0191','CSLL - Tributação Diferida/Opção pelo Simples - Lançamento de Ofício'),
('0211','IRPF - Declaração de Ajuste Anual, Declaração de Saída Definitiva do País e Declaração Final de Espólio'),
('0216','Depósito Judicial - Outros - Aduaneiros'),
('0220','IRPJ-PJ Obrigadas ao Lucro Real - Entidades não Financeiras - Balanço Trimestral'),
('0229','Depósito Administrativo - Outros - Aduaneiros'),
('0231','RPJ - Ganhos Líquidos em Operações na Bolsa - Lucro Presumido ou Arbitrado'),
('0244','Ouro Ativo Financeiro - Lançamento de Ofício'),
('0246','IRPF - Complementação Mensal'),
('0285','Parcelamento para Ingresso no Simples Nacional'),
('0289','Multa da CLT'),
('0298','Imposto de Exportação-Lançamento de Ofício'),
('0300','Receita Direitos Antidumping-Lançamento de Ofício'),
('0312','Devolução de Restituição Indevida - IRPF - Não Tributário'),
('0338','Multa Isolada Receita Direitos Antidumping e Compensatorios art. 7 Lei 9019/95'),
('0340','Juros Isolados Receita Direitos Antidumping e Compensatorios art. 7 Lei 9019/95'),
('0353','Parcelamento Timemania'),
('0381','Multa por Omissão/Erro na Dirf Anual'),
('0390','Multa por Falta ou Atraso na Entrega da Declaraçao de Informaçoes sobre Movimentaçao Financeira - Dimof'),
('0394','Contribuição Prêmios Prescritos-Lei 5.768/71'),
('0400','R D Ativa - Parcelamento para Ingresso no Simples Nacional'),
('0416','IRPJ - Regime Especial de Tributação - Patrimônio de Afetação - Lançamento de Ofício'),
('0422','IRRF - Royalties e Assistência Técnica - Residentes no Exterior'),
('0434','Cofins-Importação de Serviços-Lançamento de Ofício'),
('0439','Multa por Falta ou Atraso na Entrega da Declaraçao de Transferencia de Titularidade de Açoes Negociadas Fora da Bolsa - DTTA'),
('0445','R D Ativa - Funcafé - Leilão'),
('0447','PIS - Importação - Depósito Administrativo'),
('0449','PIS-Importação de Serviços-Lançamento de Ofício'),
('0450','IRPJ - Ganho de Capital - Alienação de Ativos de ME/EPP Optantes pelo Simples - Lançamento de Ofício'),
('0457','Receita Dívida Ativa - Contribuição Açúcar e Álcool'),
('0468','Cofins - Regime Especial de Tributação - Patrimônio de Afetação - Lançamento de Ofício'),
('0473','IRRF - Rendimentos do Trabalho e de Qualquer Natureza, como os Provenientes de Pensão, Aposentadoria, Prêmios em Concursos e Comissões - Residentes no Exterior'),
('0474','Cofins - Importaçao - Contribuiçao nao Paga devido a Suspensao'),
('0481','IRRF - Juros e Comissões em Geral - Residentes no Exterior'),
('0490','IRRF - Aplicações em Fundos de Investimento de Conversão de Débitos Externos'),
('0497','PIS - Importaçao - Nao Pago Devido a Suspensao'),
('0507','IRPJ - Ganho de Capital - Alienação de Ativos de ME/EPP Optantes pelo Simples Nacional'),
('0513','PIS - Regime Especial de Tributação - Patrimônio de Afetação - Lançamento de Ofício'),
('0520','Parcelamento - Instituições de Ensino Superior - Lei nº 10.260/01'),
('0536','R D Ativa - Parcelamento - Instituições de Ensino Superior - Lei nº 10.260/01'),
('0542','CSLL - Regime Especial de Tributação - Patrimônio de Afetação - Lançamento de Ofício'),
('0559','Multa por Falta ou Atraso na Entrega da Declaraçao de Rendimentos Pagos a Consultores por Organismos Internacionais - Derc'),
('0561','IRRF - Rendimento do Trabalho Assalariado'),
('0565','Multa por Falta ou Atraso na Entrega da Declaraçao de Beneficios Fiscais - DBF'),
('0588','IRRF - Rendimento do Trabalho sem Vínculo Empregatício'),
('0594','Multa por Falta ou Atraso na Entrega da Declaraçao Anual do Simples Nacional - DASN'),
('0610','IRRF - Rendimentos Prestação Serviços Transporte Rodoviário Internacional de Carga, Pagos Por PJ Domiciliada no País, Auferidos por Transportador Autônomo PF Residente no Paraguai'),
('0627','Multa por Falta ou Atraso na Entrega da Declaraçao sobre a Utilizaçao dos Recursos em Moeda Estrangeira Decorrentes do Recebimento de Exportaçoes - Derex'),
('0656','Multa por Falta ou Atraso na Entrega da Decalaraçao de Operaçoes com Cartoes de Credito - Decred'),
('0662','Multa por Falta ou Atraso na Entrega da Declaraçao sobre a Opçao de Tributaçao de Planos Previdenciarios - DPREV'),
('0668','IPI - Bebidas'),
('0676','IPI - Automóveis'),
('0679','PIS - Tributação de Bebidas Frias - Cervejas'),
('0685','R D Ativa - Multa do Regime Disciplinar Aplicada a Rede Arrecadadora de Receitas Federais'),
('0691','PIS - Tributação de Bebidas Frias - Demais Bebidas'),
('0692','Diversas Receitas'),
('0701','Parcelamento - Art 1º da Medida Provisoria 303/2006 - Deposito Judicial'),
('0724','PIS - Importação - Tributação de Bebidas Frias - Cervejas'),
('0733','IRPJ - Devolução de Recursos Aplicados como Redução por Reinvestimento'),
('0753','PIS - Importação - Tributação de Bebidas Frias - Demais Bebidas'),
('0760','Cofins - Tributação de Bebidas Frias - Cervejas'),
('0761','Receita da Dívida Ativa - Regime Especial de Tributação do Patrimônio de Afetação'),
('0776','Cofins - Tributação de Bebidas Frias - Demais Bebidas'),
('0782','Cofins - Importação - Tributação de Bebidas Frias - Cervejas'),
('0790','Contribuição sobre a Receita de Sorteios Realizados por Entidades Filantrópicas - Lançamento de Ofício'),
('0809','Cofins - Importação - Tributação de Bebidas Frias - Demais Bebidas'),
('0810','Receita Dívida Ativa - PIS'),
('0821','IPI - Tributação de Bebidas Frias - Cervejas'),
('0830','Parcelamento - art. 1º da Medida Provisória nº 303, de 29 de Junho de 2006 - Pessoa Jurídica Optante pelo Simples'),
('0836','Receita Dívida Ativa - Pasep'),
('0838','IPI - Tributação de Bebidas Frias - Demais Bebidas'),
('0842','Parcelamento - art. 1º da Medida Provisória nº 303, de 29 de Junho de 2006 - Demais Pessoas Jurídicas'),
('0850','IPI - Vinculado Importação - Tributação de Bebidas Frias - Cervejas'),
('0855','Cofins - Importação - Depósito Administrativo'),
('0860','Pasep - Depósito Administrativo'),
('0867','IPI - Vinculado Importação - Tributação de Bebidas Frias - Demais Bebidas'),
('0868','Pasep - Depósito Judicial'),
('0873','Parcelamento para Ingresso no Simples Nacional - 2009'),
('0879','R D Ativa - Multa Isolada - CSIRF (art. 43 da Lei nº 9.430 de 1996)'),
('0880','Devolução de Restituição Indevida - Cofins/Finsocial - Não Tributário'),
('0883','R D Ativa - Juros Isolados - CSIRF (art. 43 da Lei nº 9.430 de 1996)'),
('0896','R D Ativa - Cofins - Retenção na Fonte'),
('0906','PIS - Regime Especial de Apuração e Pagamento - Álcool'),
('0912','PIS - Importação - Regime Especial de Apuração e Pagamento - Álcool'),
('0916','IRRF - Prêmios Obtidos em Concursos e Sorteios'),
('0924','IRRF - Demais Rendimentos Capital'),
('0929','Cofins - Regime Epecial de Apuração e Pagamento - Álcool'),
('0935','Cofins - Importação - Regime Especial de Apuração e Pagamento - Álcool'),
('0941','Pagamento/Parcelamento - Artigo 1º da Medida Provisoria nº 449, de 3 de dezembro de 2008'),
('0949','R D Ativa - PIS - Retenção na Fonte'),
('0958','Pagamento/Parcelamento - Art. 3º da MP 449, de 2008'),
('0970','R D Ativa - Parcelamento para Ingresso no Simples Nacional - 2009'),
('0987','Pagamento/Parcelamento - Art. 2º da MP 449, de 2008'),
('0992','R D Ativa - CSLL - Retenção na Fonte'),
('1009','Taxa de Fiscalização Mercados Seguro, Capitalização e Previdência Privada'),
('1020','IPI - Cigarros Contendo Tabaco'),
('1038','IPI - Vinculado Importação'),
('1039','R D Ativa - Recuperação de Recursos - Finor'),
('1045','R D Ativa - Recuperação de Recursos - Finam'),
('1054','IRPF - Devolução Restituição Indevida - Tributário'),
('1065','R D Ativa - Produtos - Retido por Órgão Público'),
('1068','Pagamento Unificado - Programa Minha Casa, Minha Vida (PMCMV)/Construção ou Reforma de Creches e Pré-Escolas'),
('1070','ITR - Imposto sobre a Propriedade Territorial Rural'),
('1074','Regularização Depósitos Tributários - DJE'),
('1089','IE - Imposto Exportação - Cacau'),
('1097','IPI - Maquinas, Aparelhos e Material de Transporte'),
('1107','Multa por Falta ou Atraso na Entrega da GFIP'),
('1113','IRPJ - Simples Nacional - Lançamento de Ofício'),
('1118','R D Ativa - Medicamentos Adquiridos do Distribuidor ou Varejista - Retido por Órgão Público'),
('1134','Receita Dívida Ativa - Finsocial'),
('1136','Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - art. 1º'),
('1142','Receita Dívida Ativa - IOF'),
('1150','IOF - Operações de Crédito - Pessoa Jurídica'),
('1165','Lei nº 11.941/2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - art. 3º'),
('1171','Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Pagamento a Vista com Utilizaçao de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para Liquidar Multa e Juros'),
('1174','R D Ativa - Pneus e Câmaras-de-Ar de Borracha Adquiridos de Fabricante ou de Importador - Retido por Órgão Público'),
('1187','Contribuição sobre Receita Concurso Prognósticos'),
('1188','Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Pagamento a Vista com Utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para Liquidar Multa e Juros'),
('1194','Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - art. 1º'),
('1204','Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - art. 3º'),
('1210','Lei nº 11.941, de 2009 - PGFN - Parcelamento de Dívida Decorrente de Aproveitamento Indevido de Créditos do IPI - art. 2º'),
('1214','R D Ativa - Máquinas, Tratores, Veículos para Transporte de Passageiros, de Mercadorias, de Usos Especiais e Chassis com Motores para Veículos Automóveis - Retido por Órgão Público'),
('1230','R D Ativa - Querosene de Aviação Adquirido de Produtor ou Importador - Retido por Órgão Público'),
('1233','Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - art. 1º'),
('1240','Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinarios - art. 3º'),
('1256','Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Pagamento a Vista com Utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para Liquidar Multa e Juros'),
('1262','Lei nº 11.941, de 2009 - RFB - Demais Débitos - Pagamento a Vista com Utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para Liquidar Multa e Juros'),
('1279','Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - art. 1º'),
('1285','Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - art. 3º'),
('1291','Lei nº 11.941, de 2009 - RFB - Parcelamento de Dívida Decorrente de Aproveitamento Indevido de Créditos do IPI - art. 2º'),
('1318','IPI - Simples Nacional - Lançamento de Ofício'),
('1324','CSLL - Simples Nacional - Lançamento de Ofício'),
('1330','Cofins - Simples Nacional - Lançamento de Ofício'),
('1345','Multa Atraso Entrega DCTF'),
('1347','PIS - Simples Nacional - Lançamento de Ofício'),
('1360','Contribuição Patronal Previdenciária - Simples Nacional - Lançamento de Ofício'),
('1364','Alienação de Bens Imóveis - Lei nº 8.011/1990 e Lei nº 8.025/1990 - SPU'),
('1376','Multa por Falta ou Atraso na Entrega da DIF - Papel Imune'),
('1382','Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('1399','Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Dep Judicial'),
('1415','Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('1421','Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('1425','Emolumentos Consulares - País'),
('1433','Emolumentos Justiça Distrito Federal'),
('1438','Multa por Falta ou Atraso na Entrega da Escrituração Contábil Digital (ECD)'),
('1441','Convênios - Devolução de Saldo'),
('1444','Pagamento/Parcelamento - MP 470/2009 - RFB'),
('1460','R D Ativa - Álcool Carb Adquir Distribuidor - Retido por Órgão Público'),
('1467','Regularização de depósitos judiciais não tributários - Lei nº 12.099/2009'),
('1480','Receita Dívida Ativa - Pagamento/Parcelamento - MP 470/2009 - PGFN'),
('1484','Taxa Judicial da Justiça do Distrito Federal'),
('1492','Custas Justiça Distrito Federal'),
('1496','Devolução de Restituição Indevida - IRPJ - Não Tributário'),
('1505','Custas Judiciais - outras'),
('1506','Multa por Atraso na Entrega da DASN - SIMEI'),
('1512','Multa por Atraso na Entrega do Controle Fiscal Contábil de Transição - FCONT'),
('1513','Receita Dívida Ativa - Custas Judiciais'),
('1526','Contribuição sobre a Receita de Concursos e Prognósticos - Indesp'),
('1529','R D Ativa - Fundo de Terras e da Reforma Agrária'),
('1535','R D Ativa - Funcafé - Dação em Pagamento'),
('1539','R D Ativa - Gasol/Diesel/Gás Liquefeito Petróleo e Álcool No Varejo - Retido por Órgão Público'),
('1541','Contribuição do Adicional sobre a Receita de Concursos e Prognósticos - Indesp'),
('1548','Taxa de Fiscalização de Produtos Sob Controle do Ministério do Exército'),
('1556','Contribuição para Custeio das Pensões Militares'),
('1558','Multa Aduaneira - Remessa Expressa'),
('1570','R D Ativa - Medicamentos Adquiridos do Industrial ou Importador - Retido por Órgão Público'),
('1572','Montepio Civil'),
('1582','R D Ativa - Transporte de Passageiros - Retenção em Pagamento por Órgão Público'),
('1587','Imposto Importação - Remessa Expressa'),
('1593','Imposto Importação - Remessa Expressa - Lançamento de Ofício'),
('1595','R D Ativa - Transporte Internacional de Passageiros Empresas Nacionais - Retido por Órgão Público'),
('1599','IRPJ - PJ Obrigadas ao Lucro Real - Entidades Financeiras - Balanço Trimestral'),
('1607','Multa por Aterro Irregular - SPU'),
('1626','Multa por Atraso na Entrega da Declaração de Serviços Médicos - Dmed'),
('1632','Multa por Não Recolhimento da Estimativa - IRPJ'),
('1649','Multa por Não Recolhimento da Estimativa - CSLL'),
('1652','Taxa para Certidão Quitação CLT'),
('1655','Multa do Regime Disciplinar Aplicada à Rede Arrecadadora de Receitas Previdenciárias - Rarp'),
('1661','CPSS - Servidor Civil Ativo'),
('1684','CPSS - Servidor Civil Licenciado/Afastado'),
('1689','R D Ativa - Bens ou Serviços Adquiridos de Sociedades Cooperativas e Associações Profissionais ou Assemelhadas - Retido por Órgão Público'),
('1690','CPSS - Decisão Judicial Mandado de Segurança'),
('1691','R D Ativa - Financeiras - Retenção em Pagamento por Órgão Público'),
('1700','CPSS - Servidor Civil Inativo'),
('1703','R D Ativa - Serviços - Retenção em Pagamento por Órgão Público'),
('1708','IRRF - Remuneração Serviços Prestados por Pessoa Jurídica'),
('1717','CPSS - Pensionista Civil'),
('1723','CPSS - Servidor Civil Ativo - Precatório Judicial e Requisição de Pequeno Valor'),
('1729','R D Ativa - Combustível - Retenção em Pagamento por Órgão Público'),
('1730','CPSS - Servidor Civil Inativo - Precatório Judicial e Requisição de Pequeno Valor'),
('1731','R D Ativa - Retenção na Fonte de Contribuições sobre Pagamentos dos Estados, DF e Municípios pela Aquisição de Bens e Serviços - CSLL, Cofins e PIS'),
('1752','CPSS - Pensionista - Precatório Judicial e Requisição de Pequeno Valor'),
('1769','CPSS - Patronal - Servidor Civil Ativo - Operação Intra-Orçamentária'),
('1772','R D Ativa - Retenção na Fonte de Contribuições sobre Pagamentos de Pessoa Jurídica a outra Pessoa Jurídica de Direito Privado - CSLL, Cofins e PIS'),
('1781','CPSS - Patronal - Servidor Civil Licenciado/Afastado - Operação Intra-Orçamentária'),
('1800','IRPJ - FINOR'),
('1804','Receita Dívida Ativa - CSLL'),
('1808','CPSS - Patronal - Decisão Judicial Mandado de Segurança - Operação Intra-Orçamentária'),
('1814','CPSS - Patronal - Servidor no Exterior - Operação Intra-Orçamentária'),
('1825','IRPJ - FINAM'),
('1837','CPSS - Patronal - Precatório Judicial e Requisição de Pequeno Valor - Operação Intra-Orçamentária'),
('1838','IRPJ - FUNRES'),
('1840','Cofins - Vendas à ZMF - Substituição Tributária'),
('1843','R D Ativa - Contribuição do Plano de Seguridade Social do Servidor Público - CPSS - Patronal'),
('1850','Contribuição do Plano de Seguridade Social do Servidor Público - CPSS - Patronal - Lançamento de Ofício'),
('1872','Complemento de Contribuição Previdenciária - Recolhimento Mensal'),
('1881','Multas Previstas na Legislação de Trânsito'),
('1889','IRRF - Rendimentos Acumulados - Art. 12-A da Lei nº 7.713, de 22 de dezembro de 1988'),
('1894','Receita Dívida Ativa - Adicional ao Frete para Renovação da Marinha Mercante'),
('1895','IRRF - Rendimento Decorrente de Decisão da Justiça dos Estados/Distrito Federal, Exceto o Disposto no Artigo 12-A da Lei nº 7.713, de 22 de dezembro de 1988'),
('1905','R D Ativa - Honorários Advocatícios de Sucumbência'),
('1911','R D Ativa - Contribuição do Plano de Seguridade Social do Servidor Público - CPSS - Não Patronal'),
('1919','Parcelamento - art. 9º da Medida Provisória nº 303, de 29 de Junho de 2006 - Pessoa Jurídica Optante pelo Simples'),
('1921','PIS - Vendas à ZMF - Substituição Tributária'),
('1927','Parcelamento - art. 8º da Medida Provisória nº 303, de 29 de Junho de 2006 - Pessoa Jurídica Optante pelo Simples'),
('1928','Contribuição do Plano de Seguridade Social do Servidor Público - CPSS - Não Patronal - Lançamento de Ofício'),
('1934','Indenização Itaipú - Parcelas Vincendas'),
('1940','Devolução de Restituições não Creditadas'),
('1947','PIS - Importação - Depósito Judicial'),
('1957','Direitos de Natureza Comercial'),
('1962','II - Imposto Importação - Petróleo e Derivados'),
('1963','Direitos de Natureza Comercial - Lançamento de Oficio'),
('1970','Multa Isolada - § 6º do Art 7º da Lei nº 12.270/2010'),
('1992','Multa Isolada - § 7º do Art 7º da Lei nº 12.270/2010'),
('1994','Cofins - Importação - Depósito Judicial'),
('2009','R D Ativa - Multa Processual Penal - Tribunal de Justiça do Distrito Federal e Territórios'),
('2015','R D Ativa - Crédito Rural Securitização'),
('2021','R D Ativa - Crédito Rural - Programa Especial de Saneamento de Ativos - Pesa'),
('2030','CSLL - Entidades Financeiras - Balanço Trimestral'),
('2038','R D Ativa - Crédito Rural - Programa de Desenvolvimento do Cerrado - Prodecer II'),
('2044','R D Ativa - Crédito Rural - Programa Nacional de Fortalecimento da Agricultura Familiar - Pronaf'),
('2048','Renda Líquida da Loteria Federal Instantânea'),
('2049','Aluguéis - outros'),
('2050','ITR - Taxa de Cadastro Contribuições Área Rural'),
('2057','Arrendamentos'),
('2063','IRRF - Tributação Exclusiva sobre Remuneração Indireta'),
('2067','R D Ativa - Crédito Rural - Programa de Recuperação da Lavoura Cacaueira Baiana'),
('2073','Foros'),
('2080','Depósitos Judiciais e Extrajudiciais Administrados pela PGF-AGU'),
('2081','Laudêmios'),
('2089','IRPJ - Lucro Presumido'),
('2090','Taxa de Ocupação de Imóveis - outros'),
('2096','CP Segurados - Contribuição Segurados - Lançamento de Ofício'),
('2102','Outras Receitas Imobiliárias'),
('2110','CSLL - Operações Intra Orçamentárias'),
('2129','R D Ativa - Taxa Fisc Telecom'),
('2141','CP Patronal - Contribuição Empresa/Empregador - Lançamento de Ofício'),
('2157','Receita de Dívida Ativa - ITR e Receitas Vinculadas - Exercício de 1996 e Anteriores'),
('2158','Contribuição Riscos Ambientais/Aposentadoria Especial - Lançamento de Ofício'),
('2160','Fundaf - Selos Especiais - Cigarros'),
('2164','Contribuição Devida a Outras Entidades e Fundos - Salário Educação - Lançamento de Ofício'),
('2170','Multa por Atraso na Entrega da Dirf Anual'),
('2172','Cofins - Contribuição para Financiamento Seguridade Social'),
('2185','Multa Aplicada pelo Setor Aduaneiro - Sem Redução'),
('2187','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Rural - Senar - Lançamento de Ofício'),
('2193','Contribuição Sujeita a Retenção Previdenciária - Lançamento de Ofício'),
('2203','Multa por atraso na entrega da Escrituração Fiscal Digital da Contrib para PIS/Pasep, Contrib para o Financ Segurid Social e Contrib Previd incid sobre Receita - EFD-Contribuições'),
('2217','Juros Títulos de Renda - outros'),
('2226','Contribuição Segurado - Depósito Judicial'),
('2241','Dividendos - Bancos'),
('2249','Contribuição Devida a Outras Entidades e Fundos - Incra - Lançamento de Ofício'),
('2250','Dividendos - outras Sociedades de Economia Mista'),
('2253','Contribuição ao Fundo Nacional da Cultura - sobre Prêmios e Sorteios'),
('2255','Contribuição Devida a Outras Entidades e Fundos - Fundo Aeroviário - Lançamento de Ofício'),
('2261','Contribuição Devida a Outras Entidades e Fundos - Fundo de Desenvolvimento do Ensino Profissional Marítimo - FDEPM - Lançamento de Ofício'),
('2268','Dividendos - Empresas Publicas'),
('2276','Participações'),
('2278','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Transporte - Senat - Lançamento de Ofício'),
('2290','Contribuição Devida a Outras Entidades e Fundos - Serviço Social de Transporte - Sest - Lançamento de Ofício'),
('2294','Receita Dívida Ativa - SPU'),
('2300','Contribuição Empresa/Empregador - Depósito Judicial'),
('2313','Juros Bancários'),
('2317','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Industrial -Senai - Lançamento de Ofício'),
('2319','IRPJ - PJ Obrigadas ao Lucro Real - Entidades Financeiras - Estimativa Mensal'),
('2321','Outras Receitas Patrimoniais'),
('2323','Contribuição Devida a Outras Entidades e Fundos - Serviço Social da Industria - Sesi - Lançamento de Ofício'),
('2330','Imp Importação - Operações Intra Orçamentárias'),
('2346','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Comercial - Senac - Lançamento de Ofício'),
('2352','Contribuição Devida a Outras Entidades e Fundos - Serviço Social do Comercio - Sesc - Lançamento de Ofício'),
('2362','IRPJ- PJ Obrigadas ao Lucro Real - Entidades Não Financeiras - Estimativa Mensal'),
('2369','Cide - Sebrae/Apex/ABDI - Lançamento de Ofício'),
('2372','CSLL - PJ que Apuram o IRPJ com Base em Lucro Presumido ou Arbitrado'),
('2381','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Cooperativismo - Sescoop - Lançamento de Ofício'),
('2390','IRPJ - PJ Obrigadas ao Lucro Real - Entidades Financeiras - Declaração de Ajuste'),
('2398','Multa Isolada Compensação Previdenciária Indevida'),
('2401','IPI - Bebidas - Operações Intra Orçamentárias'),
('2408','Multa Regulamentar Descumprimento de Obrigação Acessória Previdenciária - Lançamento de Ofício'),
('2410','IPI - outros - Operações Intra Orçamentárias'),
('2414','Glosa de Compensação Previdenciária - Lançamento de Ofício'),
('2420','Multa Isolada Previdenciária - Depósito Judicial'),
('2428','IPI - Vinculado Importação - Operações Intra Orçamentárias'),
('2430','IRPJ - PJ Obrigadas ao Lucro Real-Entidades Não Financeiras-Declaração de Ajuste'),
('2450','Contribuição Devida a Outras Entidades e Fundos - Salário Educação - Depósito Judicial'),
('2456','IRPJ - PJ Não Obrigadas ao Lucro Real - Declaração de Ajuste'),
('2466','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Rural - Senar - Depósito Judicial'),
('2469','CSLL - Entidades Financeiras - Estimativa Mensal'),
('2472','Contribuição Devida a Outras Entidades e Fundos - Instituto Nacional de Colonização e Reforma Agrária - Incra - Depósito Judicial'),
('2484','CSLL - Demais PJ que Apuram o IRPJ com base em Lucro Real - Estimativa Mensal'),
('2489','Contribuição Devida a Outras Entidades e Fundos - Fundo Aeroviário - Depósito Judicial'),
('2505','Contribuição Devida a Outras Entidades e Fundos - Fundo de Desenvolvimento do Ensino Profissional Marítimo - FDEPM - Depósito Judicial'),
('2528','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Transporte - Senat - Depósito Judicial'),
('2534','Contribuição Devida a Outras Entidades e Fundos - Serviço Social de Transporte - Sest - Depósito Judicial'),
('2557','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Industrial - Senai - Depósito Judicial'),
('2563','Contribuição Devida a Outras Entidades e Fundos - Serviço Social da Industria - Sesi - Depósito Judicial'),
('2570','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Comercial - Senac - Depósito Judicial'),
('2578','Condecine - Contribuição para o Desenvolvimento da Indústria Cinematográfica Nacional'),
('2583','Multa da Susep'),
('2586','Contribuição Devida a Outras Entidades e Fundos - Serviço Social do Comércio - Sesc - Depósito Judicial'),
('2592','Cide - Sebrae/Apex/ABDI - Depósito Judicial'),
('2602','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Cooperativismo - Sescoop - Depósito Judicial'),
('2605','IRPJ - Operações Intra Orçamentárias'),
('2612','ITR - Operações Intra Orçamentárias'),
('2619','Contribuição Segurado - Depósito Administrativo'),
('2625','Contribuição Empresa/Empregador - Depósito Administrativo'),
('2654','Multa Isolada Previdenciária - Depósito Administrativo'),
('2655','Cota Parte do Adicional ao Frete para Renovação da Marinha Mercante -AFRMM'),
('2663','Serviços Administrativos - outros'),
('2671','Outros Serviços - demais'),
('2677','Contribuição Devida a Outras Entidades e Fundos - Salário Educação - Depósito Administrativo'),
('2683','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Rural - Senar - Depósito Administrativo'),
('2687','R D Ativa - Multas Previstas na Legislação sobre Defesa de Direitos Difusos'),
('2716','Contribuição Devida a Outras Entidades e Fundos - Instituto Nacional de Colonização e Reforma Agrária - Incra - Depósito Administrativo'),
('2722','Contribuição Devida a Outras Entidades e Fundos - Fundo Aeroviário - Depósito Administrativo'),
('2739','Contribuição Devida a Outras Entidades e Fundos - Fundo de Desenvolvimento do Ensino Profissional Marítimo - FDEPM - Depósito Administrativo'),
('2745','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Transporte - Senat - Depósito Administrativo'),
('2755','Serviços Administrativos - DPRF'),
('2768','IRPF - Conversão Depósito Judicial'),
('2774','Contribuição Devida a Outras Entidades e Fundos - Serviço Social de Transporte - Sest - Depósito Administrativo'),
('2780','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Industrial - Senai - Depósito Administrativo'),
('2783','IRPJ - Conversão Depósito Judicial'),
('2796','IPI - Outros - Conversão Depósito Judicial'),
('2797','Contribuição Devida a Outras Entidades e Fundos - Serviço Social da Industria - Sesi - Depósito Administrativo'),
('2808','IRRF - Conversão Depósito Judicial'),
('2810','IOF - Conversão Depósito Judicial'),
('2813','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Comercial - Senac - Depósito Administrativo'),
('2820','Contribuição Devida a Outras Entidades e Fundos - Serviço Social do Comercio - Sesc - Depósito Administrativo'),
('2836','Finsocial - Conversão Depósito Judicial'),
('2842','Cide - Sebrae/Apex/ABDI - Depósito Administrativo'),
('2849','PIS - Conversão de Depósito Judicial'),
('2851','CSLL - Conversão de Depósito Judicial'),
('2859','Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Cooperativismo - Sescoop - Depósito Administrativo'),
('2864','Honorários Advocatícios Sucumbência - PGFN'),
('2865','R D Ativa - Crédito Rural - Programa de Revitalização de Cooperativas de Produção Agropecuária - Recoop'),
('2871','R D Ativa - Multa Polícia Federal - Controle e Fiscalização de Produtos Químicos'),
('2877','Multa destinada ao Fundo de Amparo ao Trabalhador - FAT'),
('2880','Conversão Depósito Judicial - outros'),
('2888','R D Ativa - Multas Diversas - Secretaria do Patrimônio Público'),
('2892','II - Imposto Importação - Lançamento de Ofício'),
('2894','R D Ativa - Fundo de Investimentos Setoriais - Fiset - Florestamento e Reflorestamento'),
('2904','IRPF - Lançamento de Ofício'),
('2917','IRPJ - Lançamento de Ofício'),
('2927','IOF - Contrato de Derivativos'),
('2932','IRRF - Lançamento de Ofício'),
('2933','Regime de Tributação Unificada - RTU - Importação'),
('2945','IPI - Lançamento de Ofício'),
('2956','Regime de Tributação Unificada - RTU - Importação - Lançamento de Ofício'),
('2958','IOF - Lançamento de Ofício'),
('2960','Cofins - Lançamento de Ofício'),
('2973','CSLL - Lançamento de Ofício'),
('2979','Pasep - Retenção sobre as Transferências Efetuadas para Estados, DF e Municípios'),
('2985','Contribuição Previdenciária Sobre Receita Bruta - Art. 7º da Lei 12.546/2011'),
('2986','PIS - Lançamento de Ofício'),
('2991','Contribuição Previdenciária Sobre Receita Bruta - Art. 8º da Lei 12.546/2011'),
('2999','Pasep - Lançamento de Ofício'),
('3008','Royalties Até 5% - Lavra na Área Pré-Sal - Em Plataforma'),
('3014','Royalties Excedente 5% - Lavra na Área Pré-Sal - Em Plataforma'),
('3037','Participação Especial - Lavra na Área Pré-Sal'),
('3043','Lei nº 11.941, de 2009 - PGFN - Parcelamento de Dívida Decorrente de Aproveitamento Indevido de Créditos do IPI - Art. 2º - Depósito Judicial'),
('3066','Lei nº 11.941/2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º - Depósito Judicial'),
('3072','Regularização de Depósitos - Lei nº 12.099, de 2009'),
('3084','Pasep - Receita Operacional'),
('3089','Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º - Depósito Judicial'),
('3092','Pasep - Folha de Pagamento'),
('3095','Lei nº 11.941, de 2009 - RFB - Parcelamento de Dívida Decorrente de Aproveitamento Indevido de Créditos do IPI - Art. 2º- Depósito Judicial'),
('3111','Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinarios - Art. 3º- Depósito Judicial'),
('3121','PIS - Operações Intra Orçamentárias'),
('3128','Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º- Depósito Judicial'),
('3134','R D Ativa - IRPJ - Lançado de Ofício - Simples Nacional'),
('3140','R D Ativa - CSLL - Lançado de Ofício - Simples Nacional'),
('3148','Multa Isolada sobre Créditos em Pedidos de Ressarcimento ou Declaração de Compensação'),
('3157','R D Ativa - Cofins - Lançado de Ofício - Simples Nacional'),
('3163','R D Ativa - PIS - Lançado de Ofício - Simples Nacional'),
('3186','R D Ativa - IPI - Lançado de Ofício - Simples Nacional'),
('3192','R D Ativa - Contribuição Previdenciária Patronal - Lançado de Ofício - Simples Nacional'),
('3199','Multa por Atraso na Entrega da Declaração de IPI'),
('3202','R D Ativa - Contribuição Previdenciária Sobre Receita Bruta'),
('3208','IRRF - Aluguéis e Royalties Pagos a Pessoa Física'),
('3219','IRPJ - Ganho de Capital - Alienação de Ativos - Simples Nacional - Lançamento de Ofício'),
('3223','IRRF - Resgate Previdência Complementar/Modalidade Contribuição Definida/Variável - Não Optante Tributação Exclusiva'),
('3225','IRPJ - Ganhos Líquidos em Operações na Bolsa - Simples Nacional'),
('3231','Imposto Importação - Remessa Postal'),
('3248','Multa Aduaneira - Remessa Postal'),
('3249','IRRF - Ouro Ativo Financeiro'),
('3251','IRRF - Juros Caderneta de Poupança e Letras Hipotecárias - Pessoa Jurídica'),
('3254','Imposto Importação - Remessa Postal - Lançamento de Ofício'),
('3260','CSLL - Retenção na Fonte sobre Pagamentos de Pessoa Jurídica a outra Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3277','IRRF - Rendimentos de Partes Beneficiárias ou de Fundador'),
('3280','IRRF - Rem Serv Prest Associad Coop Trabalho'),
('3290','R D Ativa - Multa Destinada ao Fundo de Amparo ao Trabalhador - FAT'),
('3292','Fundaf - Ressarcimento por Cópias'),
('3300','CPSS - Não Patronal - Depósito Judicial'),
('3304','Fundaf - Demais Receitas'),
('3308','CSLL - Retenção na Fonte sobre Pagamentos de Empresa Pública, Sociedade de Economia Mista e outras Entidades a Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3316','Cofins - Retenção na Fonte sobre Pagamentos de Pessoa Jurídica a outra Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3317','IRPJ - Ganhos Líquidos em Operações na Bolsa - Lucro Real'),
('3320','IRPJ - Lucro Inflacionário'),
('3322','CPSS - Não Patronal - Depósito Administrativo'),
('3332','Cofins - Retenção na Fonte sobre Pagamentos de Empresa Pública, Sociedade de Economia Mista e outras Entidades a Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3339','R D Ativa - Pagamento Unificado - Incorporações - Programa Minha Casa, Minha Vida - PMCMV'),
('3345','IPI - Vinculado Importação - Lançamento de Ofício'),
('3351','Doações aos Fundos dos Direitos da Criança e do Adolescente'),
('3359','PIS - Retenção na Fonte sobre Pagamentos de Pessoa Jurídica a outra Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3360','PIS - Retenção na Fonte sobre Pagamentos de Empresa Pública, Sociedade de Economia Mista e outras Entidades a Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3368','R D Ativa - Pagamento Unificado - Construções - Programa Minha Casa, Minha Vida - PMCMV'),
('3373','IRPJ - PJ Não Obrigadas ao Lucro Real - Balanço Trimestral'),
('3374','Multa do Regime Disciplinar Aplicada à Rede Arrecadadora do Simples Nacional - RAS'),
('3375','IRPJ - Retenção na Fonte sobre Pagamentos de Empresa Pública, Sociedade de Economia Mista e outras Entidades a Pessoa Jurídica de Direito Privado - Lançamento de Ofício'),
('3391','Multa de Outras Origens'),
('3397','Multa Administrativa por Falta de Pagamento de Lote Arrematado em Leilão'),
('3399','Devolução de Restituição Indevida - II - Não Tributário'),
('3407','Devolução de Restituição Indevida - IE - Não Tributário'),
('3412','Devolução de Restituição Indevida - ITR - Não Tributário'),
('3413','Devolução de Restituição Indevida - IPI - Não Tributário'),
('3426','IRRF - Aplicações Financeiras de Renda Fixa - Pessoa Jurídica'),
('3436','Devolução de Restituição Indevida - IOF - Não Tributário'),
('3442','Devolução de Restituição Indevida - CSLL - Não Tributário'),
('3459','Devolução de Restituição Indevida - CIDE - Não Tributário'),
('3465','Devolução de Restituição Indevida - PIS/Pasep - Não Tributário'),
('3467','IOF - Seguros'),
('3471','Multas Previstas no Código Eleitoral e Leis Conexas'),
('3482','Multa Isolada - Contribuições Sociais e Imposto de Renda Retidos na Fonte - CSIRF (art. 43 L. 9430)'),
('3488','Multa Por Falta de Retenção na Fonte de Imposto ou Contribuição'),
('3494','Doação ao Fundo Nacional de Desenvolvimento Científico e Tecnológico - FNDCT'),
('3495','Juros Isolados - Contribuições Sociais e Imposto de Renda Retidos na Fonte - CSIRF (art. 43 L. 9430)'),
('3498','Indenizações - Demais'),
('3504','Devolução de Restituição Indevida - Contribuição Previdenciária - Não Tributário'),
('3527','Receita Dívida Ativa - Imposto Importação'),
('3533','IRRF - Provento de aposentadoria, reserva ou reforma e de pensão civil ou militar pago por Previdência da União, Estados, DF ou Municípios (regime geral ou do servidor público)'),
('3540','IRRF - Benefício previdenciário, modalidade beneficio ou contrib definido ou de contrib variável, pagos por prev. complementar ou soc. seguradora, ou Fapi, não op tribut exclusiva'),
('3543','Receita Dívida Ativa - IRPF'),
('3548','IRPJ - Cobrança'),
('3550','IRRF - Rendimento do Trabalho - Cobrança'),
('3551','Receita Dívida Ativa - IRPJ'),
('3556','IRRF - Resgate de valores acumulados relativos a planos de caráter previdenciário estruturados na modalidade de beneficio definido, não optantes pela tributação exclusiva'),
('3560','Receita Dívida Ativa - IRRF'),
('3562','IRRF - Participação dos trabalhadores nos lucros ou resultados (PLR) objeto de negociação entre a empresa e seus empregados'),
('3563','IRRF - Rendimentos de Capital - Cobrança'),
('3576','IRRF - Outros Rendimentos - Cobrança'),
('3578','Receita Dívida Ativa - IPI'),
('3579','IRRF - Resgate previdência complementar/socied. seguradora (modalidade contribuição definida/variável), seguro vida cobertura por sobrevivência ou Fapi - Optantes Trib. Exclusiva'),
('3585','R D Ativa - Contribuição para o Funttel'),
('3589','IPI - Bebidas - Cobrança'),
('3591','IPI - outros - Cobrança'),
('3601','Contribuição Previdenciária Sobre a Receita Bruta - Lançamento de Ofício'),
('3603','IOF - Cobrança'),
('3607','Restituições - outras'),
('3615','Receita Dívida Ativa - outros Tributos - Principal'),
('3616','PIS - Cobrança'),
('3618','Compensação Previdenciária Indevida em GFIP'),
('3623','Receita Dívida Ativa - Multa CLT'),
('3624','Multa por Atraso na Entrega da Escrituração Contábil Fiscal (ECF)'),
('3629','Pasep - Cobrança'),
('3630','Multa por falta ou atraso na entrega da Escrituração Fiscal Digital - EFD-ICMS/IPI'),
('3640','Receita Dívida Ativa - outras'),
('3644','Cofins - Cobrança'),
('3647','Encargos por recolhimento fora do prazo - Documento de Arrecadação do Empregador Doméstico (DAE)'),
('3653','Encargos por repasse fora do prazo - Instituição Financeira Centralizadora - Documento de Arrecadação do Empregador Doméstico (DAE)'),
('3657','CSLL - Cobrança'),
('3676','Multa por atraso no envio de informações de Alvarás e/ou Habite-se de Obras de Construção Civil por parte das Prefeituras e GDF via SisobraPref à RFB'),
('3682','Multa Isolada - Contribuições Sociais Retidas na Fonte - CSRF (art. 43 L. 9430)'),
('3690','Receita Decorrente de Bens e Valores Apreendidos - outros'),
('3699','IRRF - Rendimentos produzidos por aplicação financeira a que se refere o art. 2º da Lei nº 12.431, de 2011. (Decreto nº 7.603/2012).'),
('3703','Pasep - Pessoa Jurídica de Direito Publico'),
('3709','AFRMM - Empresa Estrangeira de Navegação ou Empresa Brasileira de Navegação, Operando Embarcação Afretada de Registro Estrangeiro'),
('3711','Juros Isolados - Contribuições Sociais Retidas na Fonte - CSRF (art. 43 L. 9430)'),
('3738','Multas Diversas Aplicadas pela Receita Federal, Exceto Aduaneira'),
('3746','Cofins - Retenção na Fonte - Aquisição de Autopeças'),
('3762','Outras Receitas Eventuais'),
('3767','AFRMM - Adicional ao Frete para Renovação da Marinha Mercante - Lançamento de Ofício'),
('3770','PIS - Retenção na Fonte - Aquisição de Autopeças'),
('3773','TUM - Taxa de Utilização do Sistema de Controle de Arrecadação do Adicional ao Frete para Renovação da Marinha Mercante (MERCANTE)'),
('3780','Reabertura Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º'),
('3796','Reabertura Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º'),
('3812','Reabertura Lei nº 11.941/2009 - PGFN - Débitos Previdenciários - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para liquidar multa e juros'),
('3829','Reabertura Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para liquidar multa e juros'),
('3835','Reabertura Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º'),
('3841','Reabertura Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º'),
('3842','IRRF - Pagamentos a Pessoa Jurídica Fornecedora de Insumos ou Transportadora de Carga que geram Direito ao Crédito Presumido'),
('3850','IRRF - Pagamentos a Pessoa Física Fornecedora de Insumos ou Transportadora Autônoma de Carga que geram Direito ao Crédito Presumido'),
('3858','Reabertura Lei nº 11.941, de 2009 - PGFN - Parcelamento Dívida Decorrente de Aproveitamento Indevido de Créditos de IPI - Art. 2º'),
('3864','Multa por Atraso/Erro/Omissão - Siscoserv'),
('3870','Reabertura Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º'),
('3877','CSLL - Pagamentos a Pessoa Jurídica Fornecedora de Insumos ou Transportadora de Carga que geram Direito ao Crédito Presumido'),
('3885','PIS - Receita Operacional'),
('3887','Reabertura Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º'),
('3890','II - Imposto Importação - Conversão Depósito Judicial'),
('3903','Reabertura Lei nº 11.941/2009 - RFB - Débitos Previdenciários - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para liquidar multa e juros'),
('3910','Reabertura Lei nº 11.941, de 2009 - RFB - Demais Débitos - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL para liquidar multa e juros'),
('3914','Parcelamento - Imóveis Extinta RFFSA - SPU'),
('3926','Reabertura Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º'),
('3928','IPI - Vinculado Importação - Conversão Depósito Judicial'),
('3932','Reabertura Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamentos Ordinários - Art. 3º'),
('3955','Reabertura Lei nº 11.941, de 2009 - RFB - Parcelamento Dívida Decorrente de Aproveitamento Indevido de Créditos de IPI - Art. 2º'),
('3961','Royalties Até 5% - Art. 2º da Lei nº 12.858/2013'),
('3978','Royalties Excedente a 5% - Art. 2º da Lei nº 12.858/2013'),
('3981','Produto Depósitos Abandonados'),
('3990','Participação Especial - Art. 2º da Lei nº 12.858/2013'),
('4007','Lei nº 12.865, de 2013 - RFB - Parcelamento PIS/COFINS - Instituições Financeiras e Cia Seguradoras - Art. 39, Caput'),
('4013','Lei nº 12.865, de 2013 - PGFN - Parcelamento PIS/COFINS - Instituições Financeiras e Cia Seguradoras - Art. 39, Caput'),
('4020','Lei 12.865, de 2013 - RFB - Parcelamento PIS/COFINS - Art. 39, § 1º'),
('4028','IOF - Ouro Ativo Financeiro'),
('4042','Lei 12.865, de 2013 - PGFN - Parcelamento PIS/COFINS - Art. 39, § 1º'),
('4059','Lei nº 12.865, de 2013 - RFB - Parcelamento IRPJ/CSLL - Art. 40'),
('4065','Lei nº 12.865, de 2013 - PGFN - Parcelamento IRPJ/CSLL - Art. 40'),
('4071','Lei nº 12.865, de 2013 - RFB - Pagamento à Vista - PIS/COFINS - Instituições Financeiras e Cia Seguradoras - Art. 39, Caput'),
('4072','Fundaf-Atividade Extraordinária de Fiscalização e Controle Aduaneiro'),
('4085','Retenção de Contribuições sobre Pagamentos dos Estados, DF e Municípios pela Aquisição de Bens e Serviços - CSLL, Cofins e PIS'),
('4088','Lei nº 12.865, de 2013 - PGFN - Pagamento à Vista - PIS/COFINS - Instituições Financeiras e Cia Seguradoras - Art. 39, Caput'),
('4094','Lei 12.865, de 2013 - RFB - Pagamento à Vista - PIS/COFINS - Art. 39, § 1º'),
('4095','Regime Especial de Tributação do Patrimônio de Afetação'),
('4104','Lei 12.865, de 2013 - PGFN - Pagamento à Vista - PIS/COFINS - Art. 39, § 1º'),
('4110','Lei nº 12.865, de 2013 - RFB - Pagamento à Vista - IRPJ/CSLL - Art. 40'),
('4112','IRPJ - Regime Especial de Tributação do Patrimônio de Afetação'),
('4127','Lei nº 12.865, de 2013 - PGFN - Pagamento à Vista - IRPJ/CSLL - Art. 40'),
('4133','R D Ativa - Contribuição Previdenciária Segurados'),
('4138','PIS - Regime Especial de Tributação do Patrimônio de Afetação'),
('4153','CSLL - Regime Especial de Tributação do Patrimônio de Afetação'),
('4156','R D Ativa - Contribuição Empresa/Empregador'),
('4162','R D Ativa - Contribuição Risco Ambiental/Aposentadoria Especial'),
('4166','Cofins - Regime Especial de Tributação do Patrimônio de Afetação'),
('4181','IRPF - Cobrança'),
('4185','R D Ativa - Contribuição Sujeita a Retenção Previdenciária'),
('4201','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Salário Educação'),
('4218','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Rural - Senar'),
('4221','IPMF - Conversão Depósito Judicial'),
('4224','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Instituto Nacional de Colonização e Reforma Agrária - Incra'),
('4230','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Fundo Aeroviário'),
('4234','Cofins - Conversão Depósito Judicial'),
('4250','Aneel - Parcelas da Reserva Global de Reversão'),
('4253','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Fundo de Desenvolvimento do Ensino Profissional Marítimo - FDEPM'),
('4260','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Transporte - Senat'),
('4262','Multa do Regime Disciplinar Aplicada a Rede Arrecadadora de Receitas Federais'),
('4263','Receita Dívida Ativa - Ressarcimentos ao Fundo Nacional de Saúde - FNS'),
('4275','CPSSS - Contribuição Patronal para o Servidor Civil'),
('4276','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Social de Transporte - Sest'),
('4282','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Industrial -Senai'),
('4288','Multa por Nota Fiscal'),
('4290','IOF - Operações Externas'),
('4298','Alienação outros Bens Móveis - outros'),
('4299','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Social da Industria - Sesi'),
('4300','Alienação do Domínio Útil de Bens Imóveis - SPU'),
('4309','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem Comercial - Senac'),
('4321','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Social do Comercio - Sesc'),
('4327','Alienação do Domínio Pleno de Bens Imóveis - SPU'),
('4335','Alienação outros Bens Imóveis - Demais'),
('4338','R D Ativa - Cide - Sebrae/Apex/ABDI'),
('4344','R D Ativa - Contribuição Devida a Outras Entidades e Fundos - Serviço Nacional de Aprendizagem do Cooperativismo - Sescoop'),
('4350','R D Ativa - Multa Isolada Compensação Previdenciária Indevida'),
('4373','R D Ativa - Multa Regulamentar Descumprimento de Obrigação Acessória Previdenciária'),
('4380','R D Ativa - Glosa de Compensação Previdenciária'),
('4396','Parcelamento de Arrematação - Primeira Parcela - Depósito Judicial'),
('4397','CSLL - Retenção na Fonte sobre Pagamentos dos Estados, DF e Municípios pela Aquisição de Bens e Serviços'),
('4406','Multa por Atraso na Entrega do PGDAS-D'),
('4407','Cofins - Retenção na Fonte sobre Pagamentos dos Estados, DF e Municípios pela Aquisição de Bens e Serviços'),
('4409','PIS - Retenção na Fonte sobre Pagamentos dos Estados, DF e Municípios pela Aquisição de Bens e Serviços'),
('4412','Reabertura Lei nº 11.941, de 2009 - PGFN - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('4429','Reabertura Lei nº 11.941, de 2009 - PGFN - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('4435','Reabertura Lei 11941/09 - PGFN - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamento Ordinário - Art. 3º - Depósito Judicial'),
('4437','Contribuição sobre Prognósticos Esportivos - Direitos Prescritos de Entidades Desportivas'),
('4464','Reabertura Lei nº 11941, de 2009 - PGFN - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamento Ordinário - Art. 3º - Depósito Judicial'),
('4470','Reabertura Lei nº 11.941, de 2009 - PGFN - Parcelamento Dívida Decorrente de Aproveitamento Indevido de Créditos de IPI - Art. 2º - Depósito Judicial'),
('4480','Receita Dívida Ativa - Multa por Infração ao Código Brasileiro de Aeronáutica'),
('4487','Reabertura Lei nº 11.941, de 2009 - RFB - Débitos Previdenciários - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('4490','Alienação Títulos Mobiliários - outros'),
('4493','Receita Dívida Ativa - Cofins'),
('4510','Reabertura Lei 11941/2009 - RFB - Débitos Previdenciários - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamento Ordinário - Art 3º - Depósito Judicial'),
('4526','Reabertura Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Dívidas Não Parceladas Anteriormente - Art. 1º - Depósito Judicial'),
('4532','Reabertura Lei nº 11.941, de 2009 - RFB - Demais Débitos - Parcelamento de Saldo Remanescente dos Programas Refis, Paes, Paex e Parcelamento Ordinário - Art. 3º - Depósito Judicial'),
('4533','Receita Dívida Ativa - Proex'),
('4549','Reabertura Lei nº 11.941, de 2009 - RFB - Parcelamento Dívida Decorrente de Aproveitamento Indevido de Créditos de IPI - Art. 2º - Depósito Judicial'),
('4562','PIS - Importação de Produtos - Lançamento de Ofício'),
('4574','PIS - Entidades Financeiras e Equiparadas'),
('4578','Encargos por Recolhimento fora do Prazo - Simples Nacional'),
('4584','Encargos por Repasse fora do Prazo - InstituiÃ§Ã£o Financeira Centralizadora - Simples Nacional'),
('4600','IRPF - Ganhos de Capital na Alienação de Bens Duráveis'),
('4601','Cota Parte - Preço de Realização de Combustível'),
('4614','Conversão Depósito Judicial - Adicional ao Frete para Renovação Marinha Mercante'),
('4617','Lei nº 12.865, de 2013 - RFB - Parcelamento PIS/COFINS - Instituições Financeiras e Cia Seguradoras - Art. 39, Caput - Depósito Judicial'),
('4623','Lei nº 12.865, de 2013 - PGFN - Parcelamento PIS/COFINS - Instituições Financeiras e Cia Seguradoras - Art. 39, Caput - Depósito Judicial'),
('4634','Devolução Restituições não Pagas IRPF'),
('4646','Lei nº 12.865, de 2013 - RFB - Parcelamento PIS/COFINS - Art. 39, § 1º - Depósito Judicial'),
('4652','Lei nº 12.865, de 2013 - PGFN - Parcelamento PIS/COFINS - Art. 39, § 1º - Depósito Judicial'),
('4675','Lei nº 12.865, de 2013 - RFB - Parcelamento IRPJ/CSLL - Art. 40 - Depósito Judicial'),
('4677','Restituições - IPI'),
('4681','Lei nº 12.865, de 2013 - PGFN - Parcelamento IRPJ/CSLL - Art. 40 - Depósito Judicial'),
('4685','Cofins - Importação de Bens - Lançamento de Ofício'),
('4698','R D Ativa - Regime Especial - Pagamento Unificado - Obras em Creches e Pré-Escolas'),
('4720','Lei nº 12.996, de 2014 - PGFN - Débitos Previdenciários - Parcelamento'),
('4737','Lei nº 12.996, de 2014 - PGFN - Demais Débitos - Parcelamento'),
('4743','Lei nº 12.996, de 2014 - RFB - Débitos Previdenciários - Parcelamento'),
('4750','Lei nº 12.996, de 2014 - RFB - Demais Débitos - Parcelamento'),
('4766','Lei nº 12.996, de 2014 - PGFN - Débitos Previdenciários - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL'),
('4772','Lei nº 12.996, de 2014 - PGFN - Demais Débitos - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL'),
('4789','Lei nº 12.996, de 2014 - RFB - Débitos Previdenciários - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL'),
('4795','Lei nº 12.996, de 2014 - RFB - Demais Débitos - Pagamento à vista com utilização de Prejuízo Fiscal e Base de Cálculo Negativa da CSLL'),
('4805','Taxa pela Utilização do Selo de Controle - Lei nº 12.995, de 2014 - Artigo 13 - Inciso I'),
('4810','Ressarcimento Financeiro - Dec 97459'),
('4811','Taxa pela Utilização dos Equipamentos Contadores de Produção - Lei nº 12.995, de 2014 - Artigo 13 - Inciso II'),
('4834','R D Ativa - Multa Isolada'),
('4840','Multa - Parcela não Restituída por Infração à Legislação - Dolo ou Má-Fé do Contribuinte - Pessoa Física'),
('4857','Contribuição Previdenciária sobre a Receita Bruta de Associações Desportivas que Mantêm Equipe de Futebol Profissional em Substituição à Contribuição Patronal -Lançamento de Ofício'),
('4863','Contribuição Previdenciária sobre a Comercialização da Produção Rural - Lançamento de Ofício'),
('4892','Lei nº 12.996, de 2014 - PGFN - Débitos Previdenciários - Parcelamento - Depósito Judicial'),
('4902','Lei nº 12.996, de 2014 - PGFN - Demais Débitos - Parcelamento - Depósito Judicial'),
('4919','Lei nº 12.996, de 2014 - RFB - Débitos Previdenciários - Parcelamento - Depósito Judicial'),
('4931','Lei nº 12.996, de 2014 - RFB - Demais Débitos - Parcelamento - Depósito Judicial'),
('4983','Parcelamento - IRPJ/CSLL - Ganho de Capital - RFB'),
('4990','Parcelamento - IRPJ/CSLL - Ganho de Capital - PGFN'),
('5006','TUM - Taxa de Utilização do Sistema de Controle de Arrecadação do Adicional ao Frete para Renovação da Marinha Mercante (MERCANTE) - Lançamento de Ofício'),
('5020','Outros Serviços Comerciais'),
('5029','IRRF - Ganho de Capital - Integralização de Cotas com Ativos - Lei nº 13.043/2014 (Art. 1º)'),
('5035','IRRF - Empréstimo de Ativos - Fundos de Investimento - Lei nº 13.043/2014 (Art. 8º)'),
('5041','Contribuição Previdenciária sobre a Folha de Pagamento de Benefícios do Regime Geral de Previdência Social'),
('5042','IPI - Devolução de Crédito Negativo'),
('5058','Regime de Tributação Simplificada - Mercadoria Importada não Identificada - Art. 67 da Lei nº 10.833/2003 - Lançamento de Ofício'),
('5064','Parcelamento Programa de Modernização da Gestão e de Responsabilidade Fiscal do Futebol Brasileiro (Profut) - Demais Débitos - RFB'),
('5087','Parcelamento Programa de Modernização da Gestão e de Responsabilidade Fiscal do Futebol Brasileiro (Profut) - Demais Débitos - PGFN'),
('5103','Devolução de Restituição Indevida - Contribuição para o Plano de Seguridade Social do Servidor - CPSS - Não Tributário'),
('5110','IPI - Tabaco e seus Sucedâneos Manufaturados, Exceto Cigarros Contendo Tabaco'),
('5123','IPI - Demais Produtos'),
('5132','Multa por Falta ou Atraso na Prestação de Informação sobre Veículo/Carga Transportada/Operação Executada'),
('5135','Tributos Extintos'),
('5149','Multa Aplicada pelo Setor Aduaneiro - Com Redução'),
('5155','Depósitos Judiciais - Royalties e/ou Participação Especial - DJE'),
('5160','Saldos de Receitas Excluídas e ou Extintas'),
('5161','Programa de Regularização Tributária Rural (PRR)'),
('5164','Contribuição sobre a Receita de Concursos e Prognósticos - Fundo Penitenciário'),
('5177','Indenizações - AGU'),
('5180','Honorários Advocatícios Sucumbência - AGU'),
('5184','Programa de Regularização Tributária (PRT) - Demais Débitos'),
('5190','Programa Especial de Regularização Tributária (PERT) - Demais Débitos'),
('5192','IRRF - Obras Audiovisuais Cinematográficas e Videofônicas ( L 8685/93) - Residentes no Exterior'),
('5200','IRRF - Rendimentos do Trabalho - Honorários Advocatícios de Sucumbência - Lei nº 13.327, de 2016'),
('5204','IRRF - Juros Indenizações Lucros Cessantes'),
('5217','IRRF - Pagamento a Beneficiário não Identificado'),
('5220','IOF - Operações de Câmbio'),
('5232','IRRF - Aplicações Financeiras em Fundos de Investimento Imobiliário'),
('5246','Royalties 5% (E/M) L 7990 art. 7 I A III - DJE'),
('5252','Royalties Até 5% - Lavra na Área Pré-Sal - Em Plataforma - DJE'),
('5260','Outras Receitas - Funpem'),
('5269','Royalties 5% (E-M) (L 7990 art. 7 P 4) - DJE'),
('5273','IRRF - Operações de Swap (art. 74 L 8981/95)'),
('5275','Cota Parte Indenização pela Extração de Petróleo, Xisto e Gás (MM) - DJE'),
('5281','Royalties Até 5% - Art. 2º da Lei nº 12.858/2013 - DJE'),
('5286','IRRF - Aplicações Financeiras de Residentes ou Domiciliados no Exterior'),
('5298','Royalties Excedentes a 5% (E/M) Lei nº 9.478/1997, art. 49, I - DJE'),
('5299','IRRF - Juros sobre Empréstimos Externos (DL 2303/86)'),
('5300','Multa Atraso Entrega Declaração ITR'),
('5303','Receita Dívida Ativa - Impostos Extintos'),
('5308','Royalties Excedentes a 5% (MCT) Lei nº 9.478/1997, art. 49, I - DJE'),
('5314','Royalties Excedente a 5% - Lavra na Área Pré-Sal - Em Plataforma - DJE'),
('5320','Multa Atraso Entrega DIRPF'),
('5337','Royalties Excedentes a 5% (E-M) - Lei nº 9.478/1997, art. 49, II - DJE'),
('5338','Multa Atraso Entrega DIPJ'),
('5343','Royalties Excedentes a 5% (MM/MCT) - Lei nº 9.478/1997, art. 49, II - DJE'),
('5350','Royalties Excedente a 5% - Art. 2º da Lei nº 12.858/2013 - DJE'),
('5366','Participação Especial (E-M) - Lei nº 9.478/1997, art. 50 - DJE'),
('5370','Receita Dívida Ativa - Crédito Rural - STN'),
('5372','Participação Especial (MME/MMA) - Lei nº 9.478/1997, art. 50 - DJE'),
('5382','Receita Dívida Ativa - outras Multas'),
('5395','Receita Dívida Ativa - Imposto Exportação'),
('5405','Participação Especial - Art. 2º da Lei nº 12.858/2013 - DJE'),
('5411','Royalties - Regime de Partilha de Produção - Alíquota de 15% - Art. 42 da Lei nº 12.351/2010 - Pré-Sal e Áreas Estratégicas'),
('5422','Receita Dívida Ativa - IPMF'),
('5428','Royalties - Regime de Partilha de Produção - Alíquota de 15% - Art. 42 da Lei nº 12.351/2010 - Pré-Sal e Áreas Estratégicas - DJE'),
('5434','PIS - Importação de Serviços'),
('5440','Multa por Atraso na Entrega (Maed) da DCTFWeb'),
('5442','Cofins - Importação de Serviços'),
('5450','Fundaf - Cópias Xerox - PGFN'),
('5457','Alienação de Bens Apreendidos - Sistema de Leilão Eletrônico'),
('5469','Fundaf-Deslocamento de Servidor para Prestar Serviço em Recinto ou Local Fora da Sede da Repartição de Expediente'),
('5470','Perdimento de Bens Apreendidos - Depósito Judicial'),
('5477','Cofins - Não-Cumulativa - Lançamento de Ofício'),
('5485','CPSSS - Contribuição Patronal Servidor Civil Inativo'),
('5492','CPSS/FCDF - Servidor Civil Ativo'),
('5493','CPSSS - Contribuição Patronal Pensionista Civil'),
('5502','CPSS/FCDF - Servidor Civil Inativo/Pensionista'),
('5503','IPI - Vinculado Importação Veículos'),
('5506','Outras Contribuições Econômicas'),
('5516','II - Imposto Importação - Veículos'),
('5519','CPSS/FCDF - Patronal'),
('5525','Programa de Regularização de Débitos Previdenciários dos Estados e dos Municípios (PREM) - MP 778/2017'),
('5529','Receita Direitos Antidumping'),
('5530','CPSSS - Contribuição do Pensionista Civil'),
('5557','IRRF - Ganhos Líquidos em Operações em Bolsas e Assemelhados'),
('5565','IRRF - Benefício previdência complementar/socied. seguradora (modalidade contribuição definida/variável), seguro vida cobertura por sobrevivência ou Fapi - Optantes Trib. Exclusiva'),
('5572','Multa Distribuição de Prêmio (s/Redução)'),
('5585','Multa Segurança Privada - DPF (Lei 9.017/95)'),
('5590','Fundaf-Vistoria Técnica e Auditoria de Sistema de Controle Informatizado-Alfandegamento-Habilitação para Despacho Aduaneiro de Local ou Recinto'),
('5602','PIS - Importação'),
('5610','Serviços Financeiros - outros'),
('5612','Outros Serviços - MICT'),
('5625','IRPJ - Lucro Arbitrado'),
('5629','Cofins - Importação'),
('5640','Transferências de Pessoas - Fundo Partidário'),
('5680','Fundo Nacional Antidrogas - DJE'),
('5697','Receita Dívida Ativa - Multa Não Tributária - RFB'),
('5706','IRRF - Juros sobre o Capital Próprio'),
('5713','Receita Dívida Ativa - Multa Não Tributária - Departamento de Polícia Federal - Fiscalização Segurança Privada'),
('5720','Multa por Omissão/Incorreção/Atraso na Prestação de Informações Relativas a Operações Realizadas com Criptoativos'),
('5736','Participação da União em Receita de Loteria Federal'),
('5742','Participação da União em Receita de Loteria Esportiva'),
('5747','Receita Cadastro Eleitoral - TSE'),
('5759','Participação da União em Receitas de Loteria de Prognósticos Numéricos'),
('5762','Custas Justiça Federal - 1º Grau'),
('5765','Participação da União em Receita de Loteria Instantânea Exclusiva'),
('5771','Participação da União em Receitas de Loteria de Prognóstico Específico'),
('5775','Custas Justiça Federal - 2º Grau'),
('5784','Restituições - Aviso MF 087/85'),
('5788','IRPJ - Suplementar'),
('5794','Multa por Omissão/Incorreção/Atraso na Entrega do Livro Caixa Digital do Produtor Rural (LCDPR)'),
('5802','CSLL - Suplementar'),
('5804','Multa por Omissão/Incorreção/Falta/Atraso na Entrega da Escrituração Fiscal Digital de Retenções e Outras Informações Fiscais (EFD-Reinf)'),
('5827','Contribuição Facultativa em Período de Benefício Emergencial com Suspensão Temporária de Contrato ou Redução de Jornada de Trabalho/Salário (Lei nº 14.020/2020)'),
('5833','Contribuição Facultativa em Período de Afastamento/Inatividade sem Remuneração e Atividade Vinculada ao RGPS/RPPS - § 5º do Art 11 e § 35 do Art 216 do RPS (Decreto nº 3.048/1999)'),
('5856','Cofins Não-Cumulativa'),
('5862','Participação da União em Receita de Loteria de Apostas de Quota Fixa'),
('5864','Transferências de Instituições Privadas - outros'),
('5869','CPMF - Lançamento Débito em Conta'),
('5871','CPMF-Oper. Liquidação/Pagamento Valores não Creditados em Conta do Beneficiário'),
('5872','Transferências do Exterior - outros'),
('5879','Transação por Adesão no Contencioso Tributário de Pequeno Valor - Demais Débitos'),
('5880','Transferências de Pessoas - outros'),
('5884','CPMF - Instituição Financeira como Contribuinte'),
('5885','Transação por Adesão no Contencioso Tributário de Pequeno Valor - Débitos Previdenciários'),
('5891','Valores Oriundos de Depósito Judicial - Processo com Arquivamento Definitivo na Justiça do Trabalho - Projeto Garimpo (Ato Conjunto CSJT.GP.CGJT nº 1, de 2019, art. 2º, § 6º)'),
('5897','Parcelamento Pessoa Física - Simples'),
('5909','Parcelamento Pessoa Jurídica - Simples'),
('5911','Receita Dívida Ativa - Avales e Fianças - Instituto do Açúcar e do Álcool'),
('5918','Valores Oriundos de Depósito Judicial- Processo com Arquivamento Definitivo na Justiça Trabalho- Projeto Garimpo- Período Pandemia (Recomendação nº 9/GCGJT, de 2020, art. 1º, § 2º)'),
('5928','IRRF - Rendimento Decorrente de Decisão da Justiça Federal, Exceto o Disposto no Artigo 12-A da Lei nº 7.713, de 22 de dezembro de 1988'),
('5930','Devolução do Auxílio Emergencial pelos Beneficiários de Outros Rendimentos Tributáveis em Valor Superior ao Valor da Primeira Faixa da Tabela Progressiva Anual do IRPF'),
('5936','IRRF - Rendimento Decorrente de Decisão da Justiça do trabalho, Exceto o Disposto no Artigo 12-A da Lei nº 7.713, de 22 de dezembro de 1988'),
('5937','Multa Regulamentar CSLL Suplementar'),
('5940','Multa Regulamentar IRPJ Suplementar'),
('5944','IRRF - Pagamento de Pessoa Jurídica a Pessoa Jurídica por Serviços de Factoring'),
('5947','Parcelamento - Recuperação Judicial - Débitos não Previdenciários Recolhíveis Originalmente em Darf - Até 120 Parcelas ou até 84 Parcelas com Utilização de PF e BCN da CSLL'),
('5952','Retenção de Contribuições sobre Pagamentos de Pessoa Jurídica a Pessoa Jurídica de Direito Privado - CSLL, Cofins e PIS'),
('5960','Cofins - Retenção sobre Pagamentos de Pessoa Jurídica a Pessoa Jurídica de Direito Privado (art. 30 da Lei nº 10.833/2003)'),
('5976','Parcelamento - Recuperação Judicial - Tributos Retidos/Descontados Recolhíveis Originalmente em Darf (IOF, IRRF, Contribuição Previdenciária) - Até 24 parcelas'),
('5978','Receita Dívida Ativa - CPMF'),
('5979','PIS - Retenção sobre Pagamentos de Pessoa Jurídica a Pessoa Jurídica de Direito Privado'),
('5980','CPMF - Conversão Depósito Judicial'),
('5982','Parcelamento - Recuperação Judicial - Débitos Patronais Recolhíveis Originalmente em Darf (Previdenciário e Contribuição Devida por Lei a Terceiros) - Até 60 Parcelas'),
('5987','CSLL - Retenção sobre Pagamentos de Pessoa Jurídica a Pessoa Jurídica de Direito Privado (art. 30 da Lei nº 10.833/2003)'),
('5993','IRPJ - Optantes pela Apuraçao com Base no Lucro Real - Estimativa Mensal'),
('6005','Parcelamento - Recuperação Judicial - Débitos Patronais Recolhíveis Originalmente em GPS (Previdenciário e Contribuição Devida por Lei a Terceiros) - Até 60 Parcelas'),
('6011','Parcelamento - Recuperação Judicial - Débitos Retidos/Descontados Recolhíveis Originalmente em GPS (Contribuição Previdenciária) - Até 24 parcelas'),
('6012','CSLL - Demais PJ que Apuram o IRPJ com Base em Lucro Real - Balanço Trimestral'),
('6015','IRPF - Ganhos Líquidos em Operações em Bolsa'),
('6023','Receita Dívida Ativa - Cide Combustíveis'),
('6028','Transação por Adesão no Contencioso Tributário de Relevante e Disseminada Controvérsia Jurídica'),
('6034','Reabertura da Transação por Adesão no Contencioso Tributário de Pequeno Valor - Demais Débitos'),
('6057','Quota Parte do Adicional ao Frete para Renovação da Marinha Mercante - AFRMM (Fundo da Marinha Mercante - FMM)'),
('6063','Parcelamento Constitucional Excepcional dos Débitos Decorrentes de Contribuições Previdenciárias dos Municípios'),
('6070','Parcelamento Parametrizado em Contingência - Débitos Previdenciários'),
('6081','ITR - Conversão Depósito Judicial'),
('6082','Receita Dívida Ativa - Cide Remessas ao Exterior'),
('6086','Perdimento de Bens, Direitos e Valores Declarados pela Justiça Federal nos Crimes Previstos na Lei nº 9.613, de 1998 - DJE'),
('6090','Serviços Processamento de Dados - Fundaf'),
('6092','Contribuições Previdenciárias - Recolhimento Exclusivo pela Justiça do Trabalho'),
('6094','Multa Isolada - CSLL (art. 43 L.9430)'),
('6102','Transação - Programa de Redução de Litigiosidade Fiscal (PRLF)'),
('6106','Simples - Pagamento de Micro Empresa e Empresa de Pequeno Porte'),
('6147','Produtos - Retenção em Pagamentos por Órgão Público'),
('6150','Combustível - Retenção em Pagamento por Órgão Público'),
('6160','R D Ativa - Comaer - Receita Proveniente de Tarifas Cobradas pela Utilização de Informações Aeronáuticas, Tráfego Aéreo, Meteorologia e Auxílios a Navegação Aérea'),
('6175','Transporte de Passageiros - Retenção em Pagamento por Órgão Público'),
('6177','Pagamento Unificado- Regime de Tributação Específica do Futebol (TEF)'),
('6183','R D Ativa - Pagamento Unificado - Regime de Tributação Específica do Futebol (TEF)'),
('6188','Financeiras - Retenção em Pagamento por Órgão Público'),
('6190','Serviços - Retenção em Pagamento por Órgão Público'),
('6197','Fundaf-Auditoria de Sistema Informatizado para Habilitação em Regime Aduaneiro Especial'),
('6228','CSLL - Retenção na Fonte sobre Pagamento a Pessoa Jurídica (art. 34 da Lei nº 10.833/2003)'),
('6230','PIS - Retenção na Fonte sobre Pagamento Efetuado por Órgão Público à Pessoa Jurídica'),
('6243','Cofins - Retenção na Fonte sobre Pagamento à Pessoa Jurídica (art. 34 da Lei nº 10.833/2003)'),
('6250','Receita de Leilões Mercadorias Apreendidas'),
('6256','IRPJ - Retenção na Fonte sobre Pagamento à Pessoa Jurídica (art. 34 da Lei nº 10.833/2003)'),
('6297','IRPJ-Ganhos de Capital na Alien. de Ativos Micro Empresa/EPP Optante pelo Simples'),
('6311','Receita Dívida Ativa - Amortização Juros Empréstimo ao Fundo de Marinha Mercante'),
('6324','Multa Isolada - PIS/Pasep (art. 43 L.9430)'),
('6337','Multa Isolada - Cofins (art. 43 L.9430)'),
('6340','Multa Isolada - Imp. Importação (art. 43 L.9430)'),
('6352','Multa Isolada - IRPF (art. 43 L.9430)'),
('6378','Multa Isolada - IRPJ (art. 43 L.9430)'),
('6380','Multa Isolada - IRRF (art. 43 L.9430)'),
('6393','Multa Isolada - IPI Vinculado (art. 43 L.9430)'),
('6402','Multa do TCU'),
('6405','Multa Isolada - IPI (art. 43 L.9430)'),
('6410','Fundaf - Selos Especiais de Controle - Outros'),
('6418','Multa Isolada - IOF (art. 43 L.9430)'),
('6420','Multa Isolada - CPMF (art. 43 L.9430)'),
('6488','Serviços de Laboratório de Análises - SRF'),
('6525','Fundaf - Ressarcimento Receitas de Recintos Alfandegados'),
('6542','Juros Imposto Importação - (art. 43 L.9430)'),
('6555','Juros IRPF - (art. 43 L.9430)'),
('6570','Juros IRPJ - (art. 43 L.9430)'),
('6583','Juros IRRF - (art. 43 L.9430)'),
('6596','Juros IPI - (art. 43 L.9430)'),
('6608','Juros IPI - Vinculado (art. 43 L.9430)'),
('6610','Juros IOF - (art. 43 L.9430)'),
('6621','Serviços de Registro do Comércio'),
('6623','Juros Cofins (art. 43 L.9430)'),
('6630','Multas Previstas na Legislação do Registro de Comércio'),
('6636','Juros PIS/Pasep - (art. 43 L.9430)'),
('6648','Parcelamento Lei 10.684/03 (Paes) - Depósito Judicial'),
('6649','Juros CSLL - (art. 43 L.9430)'),
('6651','Juros CPMF (art. 43 L.9430)'),
('6656','PIS - Não-Cumulativo - Lançamento de Ofício'),
('6677','IRPJ - FINOR - Estimativa'),
('6680','Multa por Omissão/Erro/Atraso - Declaração de Informações sobre Atividades Imobiliárias - DIMOB'),
('6692','IRPJ - FINAM - Estimativa'),
('6704','IRPJ - FUNRES - Estimativa'),
('6720','Receita Outorga Serviços de Transporte Ferroviário'),
('6732','Contribuição sobre a Receita de Concursos de Prognósticos - Crédito Educativo'),
('6744','Multa por Atraso na Entrega da Declaração de Operações Imobiliárias - DOI'),
('6758','CSLL - Entidades Financeiras - Declaração de Ajuste'),
('6773','CSLL - Demais Pessoas Jurídicas - Declaração de Ajuste'),
('6786','Superávit Financeiro Exercícios Anteriores'),
('6799','IRRF - Resgate de Fundo de Aposentadoria Programada Individual - FAPI'),
('6800','IRRF - Aplicações Financeiras em Fundos de Investimento de Renda Fixa'),
('6808','Multa por Omissão/Erro/Atraso Dacon'),
('6813','IRRF - Fundos de Investimento - Ações'),
('6824','PIS - Combustíveis'),
('6840','Cofins - Combustíveis'),
('6841','Multa por falta de comunicação da exclusão do Simples Nacional'),
('6854','IOF - Títulos ou Valores Mobiliários'),
('6875','Pneus e Câmaras-de-Ar de Borracha Adquiridos de Fabricante ou de Importador - Retido por Órgão Público'),
('6882','Multa Falta Placa Simples (C/Red)'),
('6883','Máquinas, Tratores, Veículos para Transporte de Passageiros, de Mercadorias, de Usos Especiais e Chassis com Motor para Veículos Automóveis - Retido por Órgão Público'),
('6891','IRRF - Vida Gerador de Benefício Livre - VGBL'),
('6895','IOF - Factoring (art. 58 Lei 9532/97)'),
('6904','IRRF - Rendimentos de Indenização por Danos Morais'),
('6907','Multa Empresas Inativas (Parcelamento)'),
('6910','Dividendos - Outras Empresas'),
('6912','PIS - Não Cumulativo (Lei 10.637/02)'),
('6922','Taxa Autorização Trabalho Estrangeiro'),
('6935','Indenização Itaipú - Parcelas Vencidas Até Jul/97'),
('6939','Multa de Ofício - IPI não Lançado com Cobertura de Crédito'),
('6948','Receita Dívida Ativa - Créditos Contratuais da União - STN'),
('6950','Receita Dívida Ativa - Contrato Comissão Coord Criação Cavalo Nacional (L.7291/84)'),
('7010','Outras Receitas Atividades Associadas à Outorga de Serviços Transp. Ferroviário'),
('7023','Receita Dívida Ativa - Órgão Extintos, outras Obrigações Salvo IAA e Finex/Proex'),
('7034','Encargo Legal do Decreto-Lei nº 1.025/69 - PGFN (ajuizado)'),
('7036','Juros ITR - (art. 43 L.9430)'),
('7042','Parcelamento Lei 10.684/03 - Pessoa Física'),
('7049','Multa Isolada - ITR (art. 43 L.9430)'),
('7051','ITR - Lançamento de Ofício'),
('7064','Receita Dívida Ativa - Funapol'),
('7080','Pagamento pela Retenção de Área para Exploração ou Produção'),
('7093','Parcelamento Lei 10.684/03 - Micro Empresa'),
('7104','IRPJ - Simples'),
('7114','Parcelamento Lei 10.684/03 - Empresa Pequeno Porte'),
('7118','Multa Administrativa Decorrente de Auto de Infração Lavrado por Irregularidades Constatadas pelo AFT - DJE'),
('7122','Parcelamento Lei 10.684/03 - Demais Pessoas Jurídicas'),
('7130','Multa por Atraso na Entrega da Declaração do Imposto de Renda Pessoa Física - Espólio'),
('7160','Receita Outorga Serviço Transporte Rodoviário'),
('7186','Multas Operação do Transporte Rodoviário'),
('7199','Bônus de Assinatura de Contrato de Concessão'),
('7200','PIS - Simples'),
('7202','Cauções e Garantias Diversas'),
('7213','CPMF - Lançamento de Ofício'),
('7229','Receita Dívida Ativa - Taxa Fiscalização Mercados Seguro, Capitalização e Previdência Privada'),
('7254','Royalties 5% (E/M) L 7990 art. 7 I A III'),
('7267','Royalties 5% (E-M) (L 7990 art. 7 P 4)'),
('7282','Royalties Excedentes A 5% (E/M) Lei 9.478, art. 49, I'),
('7288','ITR - Parcelamento Lei 10.684/2003 - Exercício 1997 e Posteriores'),
('7295','Royalties Excedentes a 5% (MCT) Lei 9.478, art. 49 , I'),
('7307','CSLL - Simples'),
('7309','Depósitos (Multas CLT)'),
('7310','Royalties Excedentes a 5% (E-M) Lei 9.478, art. 49,II'),
('7317','Receita Dívida Ativa - ITR - Parcelamento Lei 10.684/2003'),
('7322','Royalties Excedentes a 5% (MM/MCT) Lei 9.478, art. 49, II'),
('7335','Participação Especial (E-M) (L 9478 art. 50)'),
('7348','Participação Especial (MME/MMA) Lei 9.478, art. 50'),
('7363','II - Imposto Importação - Depósito Judicial'),
('7368','Receita da Dívida Ativa - Multa por Violação ao Código de Defesa do Consumidor'),
('7376','Receita de Dívida Ativa - Pasep - Regime Especial de Parcelamento - Lei 10.684/2003'),
('7384','Cota-Parte da Contribuição Sindical - Desvinculação de Receitas da União -DRU'),
('7389','IPI - Outros Depósito Judicial'),
('7391','IPI - Vinculado Importação Depósito Judicial'),
('7403','Cofins - Simples'),
('7405','Depósitos Abandonados'),
('7416','IRPF - Depósito Judicial'),
('7429','IRPJ - Depósito Judicial'),
('7431','IRRF - Depósito Judicial'),
('7444','IOF - Depósito Judicial'),
('7457','ITR - Depósito Judicial'),
('7460','PIS - Depósito Judicial'),
('7485','CSLL - Depósito Judicial'),
('7498','Cofins - Depósito Judicial'),
('7500','INSS - Contribuição do Empregador - Simples'),
('7501','Depósitos para quem de direito'),
('7512','CPMF - Depósito Judicial'),
('7525','Receita Dívida Ativa - Depósito Garantia / Juízo - Justiça Federal'),
('7538','II - Imposto Importação - Depósito Administrativo'),
('7540','IPI - Outros Depósito Administrativo'),
('7553','IPI - Vinculado Importação Depósito Administrativo'),
('7566','IRPF - Depósito Administrativo'),
('7581','IRPJ - Depósito Administrativo'),
('7594','IRRF - Depósito Administrativo'),
('7606','IPI - Simples'),
('7616','Receita Dívida Ativa - Empréstimo Compulsório Principal'),
('7619','IOF - Depósito Administrativo'),
('7621','ITR - Depósito Administrativo'),
('7634','PIS - Depósito Administrativo'),
('7647','CSLL - Depósito Administrativo'),
('7650','Cofins - Depósito Administrativo'),
('7659','Parcelamento - Simples Federal'),
('7662','CPMF - Depósito Administrativo'),
('7702','ICMS - Simples'),
('7728','Receita em Consignação Pagamento de Serviços Públicos ( art. 12, Dec. 2.784/98)'),
('7730','II - Imposto Importação - Trans Navios'),
('7739','Receita da Dívida Ativa - Parcelamento de Arrematação'),
('7743','IPI - Vinculado Importação Trans Navios'),
('7756','IRPJ - Trans Navios'),
('7769','IRRF - Demais Rendimentos Trans Navios'),
('7780','Multa Isolada Condecine (art.43 da Lei 9.430)'),
('7784','Cofins - Trans Navios'),
('7797','PIS - Trans Navios'),
('7809','ISS - Simples'),
('7811','Taxa Utilização Siscomex (art. 3 L 9716/98)'),
('7837','CSLL - Trans Navios'),
('7840','Juros sobre Capital Próprio'),
('7852','Receita Alienação de Ações Recebidas em Pagamento de Dividendos'),
('7865','Tarifa e Adicional sobre Passagem Aérea Internacional (MP 1792)'),
('7878','Condecine - Lançamento de Ofício'),
('7880','Multas Isoladas Diversas - Depósito Administrativo'),
('7893','IOF - Operações de Crédito - Pessoa Física'),
('7905','IOF - Aquisição de Títulos ou Valores Mobiliários'),
('7918','Receita da Dívida Ativa - Multas da Agência Nacional do Petróleo'),
('7920','IRPJ - FINOR Ajuste Anual'),
('7933','IRPJ - FINAM Ajuste Anual'),
('7940','Juros Isolados Condecine (art.43 da Lei 9.430)'),
('7946','IRPJ - FUNRES Ajuste Anual'),
('7961','Receita Dívida Ativa - Depósito Garantia / Juízo - Justiça Estadual'),
('7987','Cofins - Entidades Financeiras e Equiparadas'),
('8002','PIS - Dedução'),
('8019','Custas da Justiça do Trabalho - Lei 10.537/2002'),
('8021','Porte de Remessa e Retorno dos Autos'),
('8034','Multas Prev Infração Legislação Transporte Ferroviário'),
('8045','IRRF - Outros Rendimentos'),
('8047','Depósito Judicial - outros'),
('8050','Depósito Administrativo - outros'),
('8053','IRRF - Aplicações Financeiras de Renda Fixa - Pessoa Física'),
('8062','Receita Dívida Ativa - Multas Previstas no Código Eleitoral e Leis Conexas'),
('8102','Venda de Particip Acionária União - Telebrás'),
('8109','PIS - Faturamento'),
('8128','Multa Isolada IRPJ - Simples (art.43 L.9430)'),
('8130','Multa Isolada IPI - Simples (art.43 L.9430)'),
('8143','Multa Isolada PIS - Simples (art.43 L.9430)'),
('8156','Multa Isolada Cofins- Simples (art.43 L.9430)'),
('8168','Emolumentos da Justiça do Trabalho - Lei 10.537/2002'),
('8169','Multa Isolada CSLL - Simples (art.43 L.9430)'),
('8171','Multa Isolada INSS Empregador - Simples (art.43 L.9430)'),
('8176','Cide - Desistência de Ação Judicial (art. 21 da MP 66/02)'),
('8192','CPMF - Desistência de Ação Judicial (art. 21 da MP 66/02)'),
('8197','Multa Isolada ICMS - Simples (art.43 L.9430)'),
('8205','PIS - Repique Imposto de Renda'),
('8209','Multa Isolada ISS - Simples (art.43 L.9430)'),
('8211','Juros Isolado IRPJ - Simples (art.43 L.9430)'),
('8224','Juros Isolado IPI - Simples (art.43 L.9430)'),
('8237','Juros Isolado PIS - Simples (art.43 L.9430)'),
('8240','Juros Isolado Cofins- Simples (art.43 L.9430)'),
('8252','Juros Isolado CSLL - Simples (art.43 L.9430)'),
('8256','Cota Parte Indenização pela Extração de Petróleo, Xisto e Gás (MM)'),
('8265','Juros Isolado INSS Empregador - Simples (art.43 L.9430)'),
('8278','Juros Isolado ICMS - Simples (art.43 L.9430)'),
('8293','Juros Isolado ISS - Simples (art.43 L.9430)'),
('8301','PIS - Folha de Pagamento'),
('8459','PIS - Desistência de Ação Judicial (art. 21 da MP 66/02)'),
('8468','IRRF - Day-Trade Operações em Bolsa'),
('8470','Receita da Dívida Ativa - Multa Criminal/Justica Federal'),
('8496','PIS - Fabricação e Importação de Veículos em Substituição Tributária'),
('8504','Multa Isolada Cide - Combustíveis - (art. 43 Lei 9430/96)'),
('8510','Multa - Vale Pedágio'),
('8523','IRPF - Ganho de Capital na Alienação de Bens e Direitos e nas Liquidações e Resgates de Aplicações Financeiras, Adquiridos em Moeda estrangeira - IN SRF nº 118/2000'),
('8536','CPMF - Acão Judicial (art.s 45 e 46 da MP 2.037-21/00)'),
('8539','Emolumentos Consulares - Exterior'),
('8617','Receita Diretamente Arrecadada - STN'),
('8619','Juros Isolados Cide Combustíveis (art. 43 Lei 9430/96)'),
('8645','Cofins - Fabricação e Importação de Veículos em Substituição Tributária'),
('8651','Multa Isolada Cide Remessa ao Exterior (art. 43 Lei 9430/96)'),
('8658','Refis/Simples - Parcelamento Especial (MP 2061/00, artigo 2)'),
('8660','Juros Isolados Cide Remessa ao Exterior (art. 43 Lei 9430/96)'),
('8673','IRRF - Bingos (Decreto 3659/2000 art. 14 I)'),
('8699','Contrib sobre Receita de Bingos-Parcela Destinada à União (Dec 3659/00 art. 14 IV)'),
('8700','Taxa de Fiscalização de Vigilância Sanitária'),
('8707','Pasep - Regime Especial de Parcelamento - MP 38/2002 e Lei 10.684/03'),
('8713','Taxa de Fiscalização de Vigilância Sanitária nos portos, Aeroportos e Fronteiras'),
('8726','Álcool Carb Adquir Distribuidor-Ret Órgão Pub'),
('8739','Gasol/Diesel/Gás Liquefeito Petróleo e Álcool Varejo-Ret Órgão Público'),
('8741','Cide - Remessas ao Exterior - L. 10332/01'),
('8754','Medicamentos Adquiridos do Industrial ou Importador - Retido por Órgão Público'),
('8767','Medicamentos Adquiridos do Distribuidor ou Varejista - Retido por Órgão Público'),
('8770','Demais Combustíveis Derivados de Petróleo e Gás Natural-Retido por Órgão Público'),
('8807','Contrib s/ a Receita Bruta de Empresas Telecomun, Destinada Funttel-Dec 3737/01'),
('8810','Taxa de Fiscalização Incidente sobre Prêmio que trata Port MF N 15/2001'),
('8811','Refis - Depósito Judicial'),
('8822','Receita de Dívida Ativa - Simples'),
('8835','Transporte Internacional Cargas Efetuado Empresas Nacionais-Retido Órgão Público'),
('8848','Construção/Reparo Embarcações Pré Regist ou Regist no Reb - Retido Órgão Público'),
('8850','Transporte Internacional de Passageiros Empresas Nacionais-Retido Órgão Público'),
('8863','Bens ou Serviços Adquiridos de Sociedades Cooperativas e Associações Profissionais ou Assemelhadas - Retido por Órgão Público'),
('8876','Receita de Dívida Ativa - INSS Simples'),
('8891','Receita de Dívida Ativa - ICMS Simples'),
('8900','Receita de Dívida Ativa - ITR - Exercícios de 1997 e Posteriores'),
('8903','Receita de Dívida Ativa - ISS Simples'),
('8931','Multa Previdência Complementar (Lei Complementar nº 109, de 29/05/2001, art.65, IV)'),
('8944','II - Imposto Importação - Garantia Aduaneira/Depósito Administrativo'),
('8957','IPI - Vinculado à Importação - Garantia Aduaneira Depósito Administrativo'),
('8960','IRPF - Ganho de Capital na Alienação de Moeda Estrangeira Mantida em Espécie - IN SRF 118/2000'),
('8972','IRPJ - Previdência Complementar/Sociedade Seguradora/FAPI Optante pelo Ret (art. 2º MP nº 2.222/01)'),
('8993','Tarifa Decorrente do Serviço de Emissão e Gerenciamento de Certificados - Portaria IPI (Instituto Nacional de Tecnologia da Informação) nº 12 de 26/03/2002'),
('8998','IRPJ - IN SRF 89/2001 art. 7 Parágrafo 8'),
('9004','IRPJ - FINOR Balanço Trimestral - Pessoa Jurídica que Atenda às Condições do art. 9º da Lei 8.167/1991'),
('9013','Condecine - Pagamento, Crédito, Emprego, Entrega e Remessa para o Exterior - MP 2228/01, art. 33º, Parágrafo 2º'),
('9017','IRPJ - FINOR - Estimativa - Pessoa Jurídica que Atenda às Condições do art. 9º da Lei 8.167/1991'),
('9020','IRPJ - FINAM - Balanço Trimestral - Pessoa Jurídica que Atenda às Condições do art. 9º da Lei 8.167/1991'),
('9032','IRPJ - FINAM - Estimativa - Pessoa Jurídica que Atenda às Condições do art. 9º da Lei 8.167/1991'),
('9045','IRPJ - FUNRES - Balanço Trimestral - Pessoa Jurídica que Atenda às Condições do art. 9º da Lei 8.167/1991'),
('9058','IRPJ - FUNRES - Estimativa - Pessoa Jurídica que Atenda às Condições do art. 9º da Lei 8.167/1991'),
('9060','Querosene de Aviação Adquirido de Produtor ou Importador - Retido por Órgão Público'),
('9064','II - Imposto Importação - Adicional'),
('9073','Cofins - Desistência de Ação Judicial (art. 21 da MP 66/02)'),
('9086','IRPJ - Ganhos Líquidos Operações Bolsa Investimentos de País C/ Tributação Favorecida'),
('9090','Doações aos Fundos Controlados pelos Conselhos Municipais, Estaduais e Nacional do Idoso'),
('9100','Refis - Parcelamento Vinculado Receita Bruta'),
('9113','ITR - Parcelamento Alternativo Exercício 1996 e Anteriores'),
('9126','ITR - Parcelamento Alternativo Exercício 1997 e Posteriores'),
('9136','Multa/Juros de Transferência - SPU'),
('9139','Contribuição sobre Prêmios Prescritos de Loterias Federais'),
('9141','Contribuição sobre a Receita de Loteria Instantânea'),
('9154','Contribuição sobre a Receita de Loterias de Números'),
('9167','Contribuição sobre a Receita de Concursos Especiais de Loterias Esportivas'),
('9170','Contribuição sobre a Receita de Loterias Esportivas'),
('9182','Contribuição sobre a Receita da Loteria Federal'),
('9197','Contribuição sobre a Receita de Loteria de Apostas de Quota Fixa'),
('9207','Multa por Falta/Atraso no Recolhimento das Contribuições Instituídas pelos art. 1º e 2º da LC nº 110/2001, de que trata o Parágrafo 2º do art. 3º da Referida LC'),
('9210','IRPJ - Desistência de Ação Judicial de que trata o artigo 11 da MP nº 38, de 14/05/2002'),
('9222','Refis - Parcelamento Alternativo'),
('9235','CSLL - Desistência de Ação Judicial de que trata o artigo 11 da MP nº 38, de 14/05/2002'),
('9248','Cofins - Desistência de Ação Judicial de que trata o artigo 11 da MP nº 38, de 14/05/2002'),
('9250','PIS - Desistência de Ação Judicial de que trata o artigo 11 da MP nº 38, de 14/05/2002'),
('9263','Pasep - Desistência de Ação Judicial de que trata o artigo 11 da MP nº 38, de 14/05/2002'),
('9303','Cide - Remessa Exterior - Lei 10332/01 - Lançamento de Ofício'),
('9304','Cide - Combustíveis - Lançamento de Ofício'),
('9331','Cide - Combustíveis - Mercado Interno - Lei 10336/2001'),
('9344','IRPJ - FINOR - Ajuste Anual - Pessoa Jurídica que atenda às Condições do art. 9º da Lei 8.167/1991'),
('9360','IRPJ - FINAM - Ajuste Anual - Pessoa Jurídica que atenda às Condições do art.9º da Lei 8.167/1991'),
('9372','IRPJ - FUNRES - Ajuste Anual - Pessoa Jurídica que atenda às Condições do art. 9º da Lei 8.167/1991'),
('9385','IRRF - Multas e Vantagens'),
('9412','IRRF - Fretes Internacionais - Residentes no Exterior'),
('9427','IRRF - Remuneração de Direitos - Residentes no Exterior'),
('9438','Cide - Combustíveis - Importação - Lei 10.336/2001'),
('9440','IRPF - Ganhos Líquidos em Operações na Bolsa de Valores - Opção MP nº 16/2001'),
('9453','IRRF - Juros sobre o Capital Próprio - Residentes no Exterior'),
('9466','IRRF - Benefícios e Resgate de Previdência Privada e FAPI - Residentes no Exterior'),
('9478','IRRF - Aluguel e Arrendamento - Residentes no Exterior'),
('9479','Multa por Atraso na Entrega da Declaração da CPMF - IN 45/2001, art. 7º, II'),
('9481','IRPJ - Ganhos Líquidos em Operações na Bolsa de Valores - Pessoa Jurídica Isenta ou Sujeita ao Simples - Opção MP nº 16/2001'),
('9494','Outras Receitas - Capital'),
('9558','PIS - IN SRF 89/2001 art. 7 paragrafo 8'),
('9562','Cofins - IN SRF 89/2001 art. 7 paragrafo 8'),
('9972','Receita Decorrente de Aportes Periódicos para Compensação ao Regime Geral de Previdência Social');